# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=500)),
                ('direccion', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_terminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_editado', models.DateTimeField(auto_now=True)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Conferencia'), (2, 'Seminario'), (3, 'Congreso'), (4, 'Curso')])),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Virtual'), (2, 'Presencial')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
